const assert=require('node:assert/strict');
const {test}=require('node:test');
require('./helpers/typescript.cjs');
const {rankDocuments}=require('../src/lib/search/rank.ts');
const {normalizeSearch,keyboardAlternative}=require('../src/lib/search/normalize.ts');
const {appHref,idFromSlug}=require('../src/lib/catalog/routes.ts');
const docs=['WhatsApp','Telegram','Instagram','Spotify','TikTok','Facebook','Clash of Clans','Grand Theft Auto','Call of Duty'].map((name,i)=>({id:i+1,name,category:i>=6?'ألعاب':'تواصل',developer:i===0||i===2||i===5?'Meta':'Developer',downloads:10}));
docs.push({id:100,name:'WhatsApp Themes',developer:'Other',category:'أدوات',downloads:999999},{id:101,name:'Random App',description:'WhatsApp Telegram Instagram Spotify TikTok Facebook',downloads:9999999});
const cases={1:['WhatsApp','واتساب','واتس اب','whatsap','واتس','واتسب','وات'],2:['Telegram','تلغرام','تيليجرام','تليجرام','telegrm','tele'],3:['Instagram','انستغرام','إنستغرام','instgram','inst'],4:['Spotify','سبوتيفاي','spotif'],5:['TikTok','تيك توك','tiktok'],6:['Facebook','فيسبوك','facebook'],7:['كلاش اوف كلانس'],8:['grand theft auto','theft grand'],9:['call-of-duty','call of duty','Call Of Duty']};
for(const [id,queries] of Object.entries(cases))for(const query of queries)test(`top-ranked ${query}`,()=>assert.equal(rankDocuments(docs,query)[0]?.id,Number(id)));
test('Arabic normalization preserves display-independent spelling',()=>{assert.equal(normalizeSearch('  إِنـستغرام!! '),'انستغرام');assert.equal(normalizeSearch('على'),'علي');assert.equal(normalizeSearch('مكتبة'),'مكتبة');});
test('empty and punctuation-only searches have no results',()=>{assert.deepEqual(rankDocuments(docs,''),[]);assert.deepEqual(rankDocuments(docs,'---'),[]);});
test('unrelated/fuzzy noise is excluded',()=>{assert.deepEqual(rankDocuments(docs,'zzzzzzzzzz'),[]);assert.deepEqual(rankDocuments(docs,'elephants'),[]);});
test('developer ranking and privacy-neutral metadata',()=>{assert.deepEqual(rankDocuments(docs,'meta').slice(0,3).map(d=>d.id),[1,3,6]);});
test('curated aliases and mixed-language names work',()=>{assert.equal(rankDocuments([{id:300,name:'Photo Editor',aliases:['محرر الصور','My Editor']}],'محرر الصور')[0].id,300);assert.equal(rankDocuments([{id:301,name:'Instagram لايت'}],'instagram لايت')[0].id,301);});
test('transliteration and keyboard fallbacks are lower-ranked',()=>{assert.equal(rankDocuments(docs,'fysbwk')[0]?.id,6);const mistyped='whatsapp'.split('').map(c=>({w:'ص',h:'ا',a:'ش',t:'ف',s:'س',p:'ح'})[c]).join('');assert.equal(keyboardAlternative(mistyped),'whatsapp');assert.equal(rankDocuments(docs,mistyped)[0]?.id,1);});
test('popularity cannot beat exact names',()=>assert.equal(rankDocuments(docs,'WhatsApp')[0].id,1));
test('bounded results and deterministic ordering',()=>assert.ok(rankDocuments(docs,'meta',2).length===2));
test('stable readable app/game URLs',()=>{assert.equal(appHref({id:4,name:'Spotify',category:'Music'}),'/apps/spotify-4');assert.equal(appHref({id:8,name:'GTA San Andreas',category:'ألعاب'}),'/games/gta-san-andreas-8');assert.equal(idFromSlug('spotify-4'),4);assert.equal(idFromSlug('bad'),null);});
