import {DownloadError} from '@/lib/downloads/rules';
import {downloadHeaders} from '@/lib/downloads/http';
/** Same-origin retry form only, private and CSP restricted. No destination or signed provider URL. */
export function providerRetry(error: unknown, applicationId: number, token: unknown): Response | null {
  if(!(error instanceof DownloadError) || !['PROVIDER_UNAVAILABLE','PROVIDER_CHALLENGE','PROVIDER_TIMEOUT','PROVIDER_RATE_LIMITED','PROVIDER_BUSY','BZZHR_NOT_FOUND','INVALID_PROVIDER_RESPONSE'].includes(error.code)
    || typeof token!=='string' || !/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{43}$/.test(token))return null;
  const messages:Record<string,string>={PROVIDER_CHALLENGE:'المصدر يطلب تحققًا بشريًا مؤقتًا.',PROVIDER_TIMEOUT:'انتهت مهلة الاتصال بالمصدر.',BZZHR_NOT_FOUND:'لم يُعثر على BZZHR لهذه اللعبة.'};
  return new Response(`<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>تعذر تجهيز المصدر</title><main><h1>تعذر تجهيز المصدر</h1><p>${messages[error.code]||'مزود التحميل غير متاح مؤقتًا.'} انتظر قليلًا ثم أعد المحاولة. يسمح الطلب بثلاث محاولات خلال صلاحيته.</p><form action="/api/downloads/legacy/redeem" method="post"><input type="hidden" name="application_id" value="${applicationId}"><input type="hidden" name="token" value="${token}"><button type="submit">إعادة المحاولة بأمان</button></form><a href="/download/${applicationId}">تجهيز طلب جديد</a></main></html>`,{status:error.status,headers:{...downloadHeaders,'Retry-After':'10','Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; form-action 'self' https://bzzhr.to https://bzzhr.co https://buzzheavier.com https://www.bzzhr.to https://www.bzzhr.co https://www.buzzheavier.com https://fafda.to; frame-ancestors 'none'; base-uri 'none'"}});
}
